export const LOADING_STARTED = "LOADING_STARTED"
export const LOADING_FINISHED = "LOADING_FINISHED"
export const LOAD_CURRENT_PROD_SEGMENT_FLOWRATES = "LOAD_CURRENT_PROD_SEGMENT_FLOWRATES"
export const LOAD_VALVE_GROUP_CURRENT_FLOWRATES = "LOAD_VALVE_GROUP_CURRENT_FLOWRATES"